### ISSUE TITLE
missing file for Toon me

### ISSUE THREAD

**Issue by bricaud** [SFI-Visual-Intelligence/AI-exhibition#4]
I get this error when running the app.py:

FileNotFoundError: [Errno 2] No such file or directory: 'ArtLine_920.pkl'

**Comment by c-salomonsen** [comment]
This is due to the pre trained models `ArtLine_920.pkl` and `Toon-Me_820.pkl` are too large for GitHub to track. 

Install them by going to [AI-exhibition/art-drawing/Toon-me/models.txt](https://github.com/SFI-Visual-Intelligence/AI-exhibition/blob/749e6f1b05946f0679a69c4b28c8d487539c4a4c/art-drawing/Toon-Me/models.txt), and manually install the required packages.

We will consider implementing an install script when time permits.

Please continue this thread if any more problems related to the installation of the models arise.

**Comment by bricaud** [comment]
I have just pushed a commit to solve this issue. Works ok but the urls are hard coded in the python script.
